### ISSUE TITLE
generateId() should not rely on window to get crypto object because there is no window in worker

### ISSUE THREAD

**Issue by pawelmhm** [timonson/gentle_rpc#14]
Currently generateId() function called when creating remote is relying on window object to be available

https://github.com/timonson/gentle_rpc/blob/master/client/creation.ts#L5

IMO this is not correct, because there is no window when you launch deno worker. This means that library can't be used inside [deno workers](https://deno.land/manual@v1.26.1/runtime/workers).

## Steps to reproduce
Consider following server:

```typescript
// rpcParent.ts
import {serve} from "https://deno.land/std@0.153.0/http/server.ts";
import { respond } from "https://deno.land/x/gentle_rpc/mod.ts";

const worker = new Worker(new URL("./rpcC.ts", import.meta.url).href, { type: "module" });
worker.postMessage("hello");

const rpcMethods = {
  bye: (name: string) => {
    console.log("bye", name);
    return "bye" + name;
  },
}
serve((req) => respond(rpcMethods, req), { port:9010 });
```

and finally a worker implementation

```typescript
// file: rpcC.ts
import { createRemote } from "https://deno.land/x/gentle_rpc/mod.ts";

self.onmessage = async (e) => {
    const remote = await createRemote(new WebSocket("ws://0.0.0.0:9010"));
    const something = await remote.call("bye", ["arg1"])
    console.log(something)
    remote.socket.close()       
}

```
now if you launch parent file it will create a worker, post message, worker will try to create a remote, and it will crash with following
```
> deno run --allow-net --allow-read --allow-write --unstable --no-prompt tmp/rpcParent.ts
Listening on http://localhost:9010/
error: Uncaught (in worker "") (in promise) ReferenceError: window is not defined
  return window.crypto.getRandomValues(new Uint32Array(1))[0].toString(16);
  ^
    at generateId (https://deno.land/x/gentle_rpc@v3.3/client/creation.ts:5:3)
    at createRequest (https://deno.land/x/gentle_rpc@v3.3/client/creation.ts:24:61)
    at Remote.call (https://deno.land/x/gentle_rpc@v3.3/client/ws.ts:170:24)
    at self.onmessage (file:///home/pawel/Documents/projects/.../client.ts
```

@timonson

**Comment by timonson** [comment]
@pawelmhm do you need a new release for this, now?

**Comment by pawelmhm** [comment]
thanks very much @timonson I would prefer to have a release, I can take it from GitHub too, but if not a problem for you to make a release it would be much appreciated.
